
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Dec 25 17:48:38 UTC 2017
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int GE = 20;
  public static final int READINT = 42;
  public static final int CASE = 39;
  public static final int INTEGER = 47;
  public static final int LPAREN = 2;
  public static final int HEX = 44;
  public static final int PRINTLN = 41;
  public static final int MINUS = 12;
  public static final int TILDE = 24;
  public static final int CHARACTER = 49;
  public static final int RPAREN = 3;
  public static final int NOT = 27;
  public static final int AND = 25;
  public static final int LT = 17;
  public static final int NIL = 30;
  public static final int OR = 26;
  public static final int LAZY = 38;
  public static final int COMMA = 8;
  public static final int CALL = 35;
  public static final int DIV = 14;
  public static final int PLUS = 11;
  public static final int IF = 31;
  public static final int LE = 19;
  public static final int EOF = 0;
  public static final int AMP = 22;
  public static final int EQUAL = 16;
  public static final int TRUE = 28;
  public static final int error = 1;
  public static final int MUL = 13;
  public static final int PIPE = 23;
  public static final int MOD = 15;
  public static final int COLON = 9;
  public static final int BIN = 43;
  public static final int ELSE = 37;
  public static final int LBRACE = 4;
  public static final int VARIABLE = 48;
  public static final int LSQUARE = 6;
  public static final int READ = 36;
  public static final int RSQUARE = 7;
  public static final int FLOAT = 45;
  public static final int LET = 33;
  public static final int RBRACE = 5;
  public static final int NE = 21;
  public static final int STRING = 46;
  public static final int PROC = 34;
  public static final int DEF = 32;
  public static final int AT = 10;
  public static final int FALSE = 29;
  public static final int GT = 18;
  public static final int PRINT = 40;
}

