
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Jan 01 12:13:23 UTC 2018
//----------------------------------------------------

package smpl.syntax;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int GE = 22;
  public static final int READINT = 45;
  public static final int CASE = 42;
  public static final int INTEGER = 50;
  public static final int LPAREN = 3;
  public static final int HEX = 47;
  public static final int PRINTLN = 44;
  public static final int MINUS = 13;
  public static final int TILDE = 26;
  public static final int CHARACTER = 52;
  public static final int RPAREN = 4;
  public static final int NOT = 29;
  public static final int AND = 27;
  public static final int LT = 19;
  public static final int NIL = 32;
  public static final int OR = 28;
  public static final int LAZY = 41;
  public static final int COMMA = 9;
  public static final int CALL = 37;
  public static final int DIV = 15;
  public static final int PLUS = 12;
  public static final int ASSIGN = 2;
  public static final int IF = 33;
  public static final int LE = 21;
  public static final int EOF = 0;
  public static final int AMP = 24;
  public static final int EQUAL = 18;
  public static final int TRUE = 30;
  public static final int error = 1;
  public static final int MUL = 14;
  public static final int PIPE = 25;
  public static final int HAT = 17;
  public static final int MOD = 16;
  public static final int COLON = 10;
  public static final int BIN = 46;
  public static final int ELSE = 39;
  public static final int LBRACE = 5;
  public static final int VARIABLE = 51;
  public static final int LSQUARE = 7;
  public static final int READ = 38;
  public static final int RSQUARE = 8;
  public static final int FLOAT = 48;
  public static final int LET = 35;
  public static final int THEN = 40;
  public static final int RBRACE = 6;
  public static final int NE = 23;
  public static final int STRING = 49;
  public static final int PROC = 36;
  public static final int DEF = 34;
  public static final int AT = 11;
  public static final int FALSE = 31;
  public static final int GT = 20;
  public static final int PRINT = 43;
}

